package com.arat.budget.model;
// default package
// Generated Jun 4, 2015 4:39:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Budget generated by hbm2java
 */
public class Budget implements java.io.Serializable {

	private long id;
	private Date purchageDt;
	private String month;
	private String year;

	public Budget() {
	}

	public Budget(long id, Date purchageDt) {
		this.id = id;
		this.purchageDt = purchageDt;
	}

	public Budget(long id, Date purchageDt, String month, String year) {
		this.id = id;
		this.purchageDt = purchageDt;
		this.month = month;
		this.year = year;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Date getPurchageDt() {
		return this.purchageDt;
	}

	public void setPurchageDt(Date purchageDt) {
		this.purchageDt = purchageDt;
	}

	public String getMonth() {
		return this.month;
	}

	public void setMonth(String month) {
		this.month = month;
	}

	public String getYear() {
		return this.year;
	}

	public void setYear(String year) {
		this.year = year;
	}

}
