package com.arat.budget.model;


// Generated Jun 16, 2015 1:57:30 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private String username;
	private String password;
	private byte enabled;
	private Set userRoleses = new HashSet(0);

	public Users() {
	}

	public Users(String username, String password, byte enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public Users(String username, String password, byte enabled, Set userRoleses) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.userRoleses = userRoleses;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	public Set getUserRoleses() {
		return this.userRoleses;
	}

	public void setUserRoleses(Set userRoleses) {
		this.userRoleses = userRoleses;
	}

	public boolean isEnabled() {
		if(this.enabled == 1)
			return true;
		else			
			return false;
	}

}
